apiVersion: apps/v1
kind: Deployment
metadata:
  name: demob-app
  labels:
    app: demob-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : demob-app
  template:
    metadata:
      labels:
        app: demob-app
    spec:
      containers:
      - name: demob-app
        image: demob
        imagePullPolicy: Never
        ports:
          - containerPort: 8100
  
---
apiVersion: v1
kind: Service
metadata:
  name: demob-svc
spec:
  ports:
    - targetPort: 8100
      port: 80
  selector:
    app: demob-app