apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demob-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: demob.com
    http:
      paths:
      - path: /
        pathType: Exact  
        backend:
          service:
            name: demob-svc
            port: 
              number: 80
